#!/bin/bash

# Author: Lawernce Onaulogho
# Desc: File exist conditional
# Date: 20/20/2020
# Date Modified: 20/20/2020

clear
if [ -e /home/lawrenzo/scripts/error.txt ]
	then
	echo "File exist"
	else
	echo "File does not exist"
	fi
