#!/bin/bash

# Author: Lawrence Onaulogho
# Desc: Variable context
# Date: 20/20/2020
# Date Modified: 20/20/2020

a=`date | awk '{print $1}'`
echo $a
if [ "$a" == Mon ]
	then
	echo Today is $a
	else
	echo Today is not Monday
fi
